import { IXbrlDTO } from '../types/IXbrlDTO';

const content1 =
  "<h3><span style=\"font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;\">Shall I compare thee to a summer’s day?</span></h3><p><span style=\"font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;\">Shall I compare thee to a summer’s day?</span><br><span style=\"font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;\">Thou art more lovely and more temperate:</span><br><span style=\"font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;\">Rough winds do shake the darling buds of May,</span><br><span style=\"font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;\">And summer’s lease hath all too short a date;</span><br><span style=\"font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;\">Sometime too hot the eye of heaven shines,</span><br><span style=\"font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;\">And often is his gold complexion dimm'd;</span><br><span style=\"font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;\">And every fair from fair sometime declines,</span><br><span style=\"font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;\">By chance or nature’s changing course untrimm'd;</span><br><span style=\"font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;\">But thy eternal summer shall not fade,</span><br><span style=\"font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;\">Nor lose possession of that fair thou ow’st;</span><br><span style=\"font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;\">Nor shall death brag thou wander’st in his shade,</span><br><span style=\"font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;\">When in eternal lines to time thou grow’st:</span><br><span style=\"font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;\">&nbsp; So long as men can breathe or eyes can see,</span><br><span style=\"font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;\">&nbsp; So long lives this, and this gives life to thee.</span></p>";

export const ixbrlDTO1: IXbrlDTO = {
  documentId: "12",
  data: content1,
  version: 1
};
